/* Full-featured mock backend for binding tests. Returns a tiny valid PNG. */
#include "../gosr.h"
#include <stdlib.h>
#include <string.h>
#include <stdio.h>

struct gosr_handle {
    char algo[16];
    int scale;
    int loaded;
    char model[256];
};

/* 1x1 RGB PNG generated by image/png; valid per RFC 2083. */
static const unsigned char kPNG[] = {
    0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a,0x00,0x00,0x00,0x0d,
    0x49,0x48,0x44,0x52,0x00,0x00,0x00,0x01,0x00,0x00,0x00,0x01,
    0x08,0x02,0x00,0x00,0x00,0x90,0x77,0x53,0xde,0x00,0x00,0x00,
    0x10,0x49,0x44,0x41,0x54,0x78,0x9c,0x62,0x3a,0x71,0xe9,0x0e,
    0x20,0x00,0x00,0xff,0xff,0x04,0xe4,0x02,0x79,0xd2,0xa8,0xca,
    0x71,0x00,0x00,0x00,0x00,0x49,0x45,0x4e,0x44,0xae,0x42,0x60,
    0x82
};

int gosr_abi_version(void) { return GOSR_ABI_VERSION; }

gosr_handle *gosr_create(const char *algorithm, int scale,
                         char *errbuf, size_t errlen) {
    (void)errbuf; (void)errlen;
    if (!algorithm) return NULL;
    gosr_handle *h = (gosr_handle *)calloc(1, sizeof(*h));
    snprintf(h->algo, sizeof(h->algo), "%s", algorithm);
    h->scale = scale;
    return h;
}

void gosr_destroy(gosr_handle *h) { free(h); }

int gosr_load_model(gosr_handle *h, const char *path,
                    char *errbuf, size_t errlen) {
    if (!h || !path) {
        if (errbuf) snprintf(errbuf, errlen, "bad args");
        return GOSR_ERR_INVALID;
    }
    /* "missing" is the test sentinel for a nonexistent model. */
    if (strstr(path, "missing") != NULL) {
        snprintf(errbuf, errlen, "model file not found: %s", path);
        return GOSR_ERR_MODEL;
    }
    /* "garbage" denotes an existing but unparsable model. */
    if (strstr(path, "garbage") != NULL) {
        snprintf(errbuf, errlen, "cannot parse model: %s", path);
        return GOSR_ERR_BAD_MODEL;
    }
    snprintf(h->model, sizeof(h->model), "%s", path);
    h->loaded = 1;
    return GOSR_OK;
}

int gosr_upsample(gosr_handle *h, const unsigned char *in, size_t in_len,
                  unsigned char **out, size_t *out_len,
                  char *errbuf, size_t errlen) {
    if (!h || !in || in_len == 0 || !out || !out_len) {
        if (errbuf) snprintf(errbuf, errlen, "bad args");
        return GOSR_ERR_INVALID;
    }
    if (!h->loaded) {
        snprintf(errbuf, errlen, "no model loaded");
        return GOSR_ERR_INVALID;
    }
    /* PNG signature check; anything else is reported as corrupt image. */
    static const unsigned char sig[8] = {0x89,'P','N','G',0x0d,0x0a,0x1a,0x0a};
    if (in_len < 8 || memcmp(in, sig, 8) != 0) {
        snprintf(errbuf, errlen, "image decode failed: not a PNG");
        return GOSR_ERR_BAD_IMAGE;
    }
    unsigned char *buf = (unsigned char *)malloc(sizeof(kPNG));
    if (!buf) { snprintf(errbuf, errlen, "oom"); return GOSR_ERR_INTERNAL; }
    memcpy(buf, kPNG, sizeof(kPNG));
    *out = buf;
    *out_len = sizeof(kPNG);
    return GOSR_OK;
}

void gosr_free(void *p) { free(p); }

int gosr_supports(int capability) {
    if (capability == GOSR_CAP_CPU) return 1;
    if (capability == GOSR_CAP_CUDA) return 0;
    return 0;
}
